### ISSUE TITLE
Implementationschancen für Ethernet via USB-C vs zusätzliche Hardware abwägen

### ISSUE THREAD

**Issue by HannesGitH** [HannesGitH/SWP_Telematik#25]
Implementationschancen für Ethernet via USB-C vs zusätzliche Hardware ist abzuwägen

_Originally posted by @HannesGitH in https://github.com/HannesGitH/SWP_Telematik/issues/3#issuecomment-753544808_

**Comment by HannesGitH** [comment]
ggf. anschließend #22 bearbeiten

wobei ich auf usb-c hoffe

**Comment by KurfuerstPilz** [comment]
Für Wiznet habe ich gesehen dass es Beispielimplementierung mit einem TCP/IP-Stack gibt (https://www.youtube.com/watch?v=zsLQm6SgL_c), allerdings ist das Video weder Englisch noch Deutsch. Verwiesen werden dort allerdings auf Quellen, die bereits im Issue #3 erwähnt wurden, d.h. die Informationen scheinen sich zu decken.

Ich meine mich andererseits daran erinnern zu können, dass in der FreeRTOS Dokumentation etwas über Kompatibilität zu Belkin stand, die wiederum einen entsprechenden USB-C zu Ethernet-Adapter anbieten. Allerdings war ich nicht in der Lage die entsprechende Doku zu finden.

Ansonsten war das was ich zu den Wiznet Chip finden konnte ausführlicher als das was ich zu den einzelnen USB-C zu Ethernet Adaptern finden konnte.

**Comment by HannesGitH** [comment]
ja das wäre eine Möglichkeit..

Ich hab jetzt ca. 2h recherchiert und finde die ethernet via usb-c Ressource nichtmehr.. Und mittlerweile befürchte ich auch, dass dem Board entsprechende Hardware fehlt.

**Comment by HannesGitH** [comment]
Ich bin noch im Besitz von zwei ESP32-DevBoards mit WLAN (IEEE 802.11 b/g/n).
Wäre noch eine weitere Überlegung, die beiden Boards (nucleo und esp) mit einander zu  verbinden, allerdings hilft das Ja auch nur begrenzt, da es wahrscheinlich ziemlich kompliziert ist die IP-Sockets auf dem Nucleo laufen zu lassen, und den LAN-Chip des ESPs zu verwenden..

**Comment by HannesGitH** [comment]
Daher würde ich dazu Tendieren die Sicherheitslücke nur zu simulieren und zu sagen: "Das wäre, wenn"

**Comment by KurfuerstPilz** [comment]
I have condidered that idea as well. The question is whether we actually circumvent the actual issue of the missing Hardware as we need mbedtls, at least to reproduce the issue that FreeRTOS+TCP uses mbedtls in a wrong manner.

Or did you have something different in mind?

Otherwise might this be an idea to split the work: One of us tries to simulate the attack - in whatever way - and the other tries to run FreeRTOS+TCP
