### ISSUE TITLE
welche TCP/IP Stack implementationen sind bereits vorhanden?

### ISSUE THREAD

**Issue by HannesGitH** [HannesGitH/SWP_Telematik#26]
welche TCP/IP Stack implementationen sind bereits implementiert und (bis zu welchem Grad) verwendbar?

_Originally posted by @HannesGitH in https://github.com/HannesGitH/SWP_Telematik/issues/3#issuecomment-753545039_

**Comment by KurfuerstPilz** [comment]
As far as the FreeRTOS+TCP demos go, there appears to be just one demo for the Windows Simulator
https://www.freertos.org/embeddedtcp.html

On FreeRTOS.org are some other demos available as well - two of them use the Wiznet Hardware - but these are legacy demos predating FreeRTOS+TCP
https://www.freertos.org/embeddedtcp.html

**Comment by KurfuerstPilz** [comment]
Abgebrochen auf Grund neuer Projektidee
