### ISSUE TITLE
New dev Branch: SecureFault after NonSecure_Init

### ISSUE THREAD

**Issue by KurfuerstPilz** [HannesGitH/SWP_Telematik#27]
Currently I receive a SecureFault when I try to run the current version in the dev-branch. I resolved this Issue previously by using the example code provided by STM.
I can't exactly tell why this error occurs as this project is based on the working project provided by STM, however, there are two general options why this doesn't work:
1: Something was removed that we needed
2: It might have something to do with the RGB Strip

**Comment by HannesGitH** [comment]
probably 1.

But thats weird anyway, imma have a look at it soon

**Comment by HannesGitH** [comment]
does it work if you set TZEN=0 ?

**Comment by KurfuerstPilz** [comment]
If Trustzone is disabled the Download fails, which makes sense - at least in the way I understand TrustZone - as the bank in which the program should be loaded is not configured correctly (please correct me if I misunderstood something wrong here). I'll submit the configuration of these banks as well. If you could see if these are identical to your configurations or if you could post your configuration we may rule out another cause of failure as well as document the necessary configuration for the project
![Bug_Issue_27](https://user-images.githubusercontent.com/49195930/103486025-0d49c300-4dfb-11eb-8639-1d92271e6ea4.PNG)

**Comment by HannesGitH** [comment]
this might be closely related to #28 

you might want to pull dev again (after #29 was succesful)

**Comment by KurfuerstPilz** [comment]
the issue - unfortunately - remains. but I have seen something I haven't seen last time: the p9813controller.c file is missing.

If I try to just build the NonsSecure-Project ther is a message saying: "No rule to make target C:/PATH/NonSecure/Src/p918controller.c" (The PATH is your absolute path. We have to see whether we can use relative paths to avoid such errors in the future. I have to check my project on the FreeRTOS+TCP Branch for that as well)

I tried to add the file via properties but that didn't resolve the issue. My guess is that the IDE expects something in that hardcoded directory. If you could explain how I can remove that entry I might be able to get the curent version running

In general we might have to see if we can find a portable way to share these projects as we know now how to add files

**Comment by HannesGitH** [comment]
hab die Pfade mal relativ gemacht, kannst nochmal die neuste dev Version probieren

(siehe https://github.com/HannesGitH/SWP_Telematik/commit/568226c0b3168280ba6cdb36772fc680de47a49a#diff-89fbea1ede6ba6d0924d028579c8165a64d38668fff5a25a96db26796f6b73a9)

**Comment by KurfuerstPilz** [comment]
the good thing is the issue of the idea not finding the IDE is resolved that's good

the bad thing is that the IDE is not able to find some functions. I'll share the part of the log describing the error:

Application/User/main.o: In function `main':
C:/Users/Maste/git/SWP_Telematik/Demonstrator/NonSecure/Src/main.c:101: undefined reference to `SECURE_RegisterCallback'
C:/Users/Maste/git/SWP_Telematik/Demonstrator/NonSecure/Src/main.c:104: undefined reference to `SECURE_RegisterCallback'
Drivers/CMSIS/system_stm32l5xx_ns.o: In function `SystemCoreClockUpdate':
C:/Users/Maste/git/SWP_Telematik/Demonstrator/NonSecure/Src/system_stm32l5xx_ns.c:227: undefined reference to `SECURE_SystemCoreClockUpdate'
Middlewares/FreeRTOS/port.o: In function `vPortSVCHandler_C':
C:/Users/Maste/git/SWP_Telematik/Dependencies/FreeRTOS/Source/portable/GCC/ARM_CM33/non_secure/port.c:580: undefined reference to `SecureContext_AllocateContext'
C:/Users/Maste/git/SWP_Telematik/Dependencies/FreeRTOS/Source/portable/GCC/ARM_CM33/non_secure/port.c:585: undefined reference to `SecureContext_LoadContext'
C:/Users/Maste/git/SWP_Telematik/Dependencies/FreeRTOS/Source/portable/GCC/ARM_CM33/non_secure/port.c:595: undefined reference to `SecureContext_FreeContext'
C:/Users/Maste/git/SWP_Telematik/Dependencies/FreeRTOS/Source/portable/GCC/ARM_CM33/non_secure/port.c:606: undefined reference to `SecureInit_DePrioritizeNSExceptions'
C:/Users/Maste/git/SWP_Telematik/Dependencies/FreeRTOS/Source/portable/GCC/ARM_CM33/non_secure/port.c:609: undefined reference to `SecureContext_Init'
Middlewares/FreeRTOS/portasm.o: In function `PendSV_Handler':
C:/Users/Maste/git/SWP_Telematik/Dependencies/FreeRTOS/Source/portable/GCC/ARM_CM33/non_secure/portasm.c:219: undefined reference to `SecureContext_SaveContext'
C:/Users/Maste/git/SWP_Telematik/Dependencies/FreeRTOS/Source/portable/GCC/ARM_CM33/non_secure/portasm.c:219: undefined reference to `SecureContext_LoadContext'
collect2.exe: error: ld returned 1 exit status
make: *** [makefile:77: Demonstartor_NonSecure.elf] Error 1
"make -j4 all" terminated with exit code 2. Build might be incomplete.

15:23:52 Build Failed. 11 errors, 0 warnings. (took 11s.212ms)

**Comment by KurfuerstPilz** [comment]
It would be probably best that we resolve these issues live, as you suggested before

**Comment by HannesGitH** [comment]
siehe: https://github.com/HannesGitH/SWP_Telematik/issues/13#issuecomment-747668458

**Comment by KurfuerstPilz** [comment]
Solved with fix for issue #13
