### ISSUE TITLE
TCP/IP with STM NUCLEO-BoardL552ZE-Q

### ISSUE THREAD

**Issue by KurfuerstPilz** [HannesGitH/SWP_Telematik#3]
We have to figure out a way to create a TCP-Socket (with FreeRTOS) and connect to the Board remotely, perhaps further Hardware might be required

**Comment by HannesGitH** [comment]
https://www.freertos.org/FreeRTOS-Plus/FreeRTOS_Plus_TCP/index.html

**Comment by KurfuerstPilz** [comment]
We need additional Hardware to be able to use FreeRTOS+TCP Library. The question that arrises is how to port FreeRTOS+TCP given that we need to work with a Driver we currently do not use.
I'll post some sites that have been useful to me since I tried to port FreeRTOS+TCP:

1: https://docs.aws.amazon.com/freertos/latest/portingguide/porting-freertos-tcp.html
This site explains how to port FreeRTOS+TCP to a MCU. We will have to define our own NetworkInterface.c
2: https://www.carminenoviello.com/2015/08/28/adding-ethernet-connectivity-stm32-nucleo/
An article which recommends a Network Processor we might want to use.
3: https://github.com/Wiznet/ioLibrary_Driver
The ioLibrary that we should use with the Network Processor

It might be useful to creat subtasks which ultimately lead to TCP/IP working on our boards.

**Comment by HannesGitH** [comment]
Implementationschancen für Ethernet via USB-C vs zusätzliche Hardware ist abzuwägen

**Comment by HannesGitH** [comment]
welche TCP/IP Stack implementationen sind bereits implementiert und (bis zu welchem Grad) verwendbar?

**Comment by HannesGitH** [comment]
Close this issue (#3) , #26, #25 ,  and open "Simulating IP-Vulnarability freeRTOS" ?

See: https://github.com/HannesGitH/SWP_Telematik/issues/25#issuecomment-754714245

**Comment by KurfuerstPilz** [comment]
Abgebrochen auf Grund neuer Projektidee
