### ISSUE TITLE
try to access Secure from Non-Secure

### ISSUE THREAD

**Issue by HannesGitH** [HannesGitH/SWP_Telematik#35]
without the secure function beeing in NonSecure Callable

should throw an error 

idau oder so muss dann meckern

**Comment by HannesGitH** [comment]
also: run with tzen=0

**Comment by KurfuerstPilz** [comment]
https://metebalci.com/blog/hello-trustzone/

Describes some Background on how to change from Nonsecure to Secure and vice versa

**Comment by HannesGitH** [comment]
the attack is no longer on the LEDController / the IDAU/SAU but on the GPIO i.e. the GTZC itself. (see #60)

**Comment by HannesGitH** [comment]
but if we choose to solve #70, we could start using this kind of attack again
