### ISSUE TITLE
access Secure from NonSecure with tzen=0

### ISSUE THREAD

**Issue by HannesGitH** [HannesGitH/SWP_Telematik#36]
also: run with tzen=0

_Originally posted by @HannesGitH in https://github.com/HannesGitH/SWP_Telematik/issues/35#issuecomment-758717599_

this should work since the concept of secure is disabled

**Comment by HannesGitH** [comment]
for this we need to run it as a whole project (only one giant memory block, no difference between ns and s)

**Comment by KurfuerstPilz** [comment]
We currently have a project to perform an attack while TZEN = 0. We may need to adapt the project in the following ways: 
- The LED-Controller should be added
- The BSP-Driver should be added

**Comment by HannesGitH** [comment]
duplicate of #54
