### ISSUE TITLE
Create Troubleshooting guide

### ISSUE THREAD

**Issue by HannesGitH** [HannesGitH/SWP_Telematik#42]
[here](https://github.com/HannesGitH/SWP_Telematik/wiki/double-trouble-%3F)

and put things we shall not forget here

**Comment by HannesGitH** [comment]
include #13 

https://github.com/HannesGitH/SWP_Telematik/issues/9#issuecomment-756994762_

**Comment by HannesGitH** [comment]
- Dateien zum Projekt hinzufügen 
    - sowohl via .project 
    - als auch via CubeIDE -> Hinzufügen

**Comment by HannesGitH** [comment]
- Standartlösung : 
> ### project-> clean -> all
> and 
> ### build secure
> ### build nonsecure

_siehe https://github.com/HannesGitH/SWP_Telematik/issues/13#issuecomment-747668458_

lvl2:  total reset via programmer : erase
lvl3:  short some pins as mentioned [here](https://github.com/HannesGitH/SWP_Telematik/issues/42#issuecomment-766974426)

**Comment by HannesGitH** [comment]
@KurfuerstPilz du müsstest da irgendwo mal den eintrag machen für was passiert wenn man RDP=2 gesetzt hat und das zeug dazu

**Comment by HannesGitH** [comment]
`Error! Failed to read target status `

**Comment by HannesGitH** [comment]
the cube-programmer installation is kinda weird and doesnt show up in the windows search so remember installation-path

add to #42 or #9

**Comment by HannesGitH** [comment]
some simple stuff:
- disconnect cubeprogrammer when flashing a new sketch
-

**Comment by KurfuerstPilz** [comment]
If you have issues while calling osDealy in your FreeRTOS task, you may want to increase the stack size

**Comment by HannesGitH** [comment]
Also it might be useful to add a "problem" Tag for our issues and link this tag in the troubleshooting guide
