### ISSUE TITLE
User Button Interrupt

### ISSUE THREAD

**Issue by KurfuerstPilz** [HannesGitH/SWP_Telematik#47]
The user button is currently working with polling. However, creating an attacking thread after an interrupt seems to be more clean. We want to check whether this works

**Comment by HannesGitH** [comment]
- either create an ISP calling a NS function 
    - either toggles a Bool-Pointer -> a thread checks if this bool -> toggles leds red if yes
    - or directly toggles LEDs red
- or a thread checking for the Button-State every ~200ms

**Comment by HannesGitH** [comment]
> * either create an ISP calling a NS function
>   
>   * either toggles a Bool-Pointer -> a thread checks if this bool -> toggles leds red if yes
>   * or directly toggles LEDs red
> * or a thread checking for the Button-State every ~200ms

in the second version the GPIO pin for the user button has to be NS , so we'll try the first one

**Comment by Poohl** [comment]
In case you are stuck on the ISR-approach: See my post here https://git.imp.fu-berlin.de/weip00/paul_weiss_bachelor/-/issues/1#note_62103, I got the button to trigger Interrupts and callback to secure.
