### ISSUE TITLE
Read some docs

### ISSUE THREAD

**Issue by HannesGitH** [HannesGitH/SWP_Telematik#5]
- [x] https://www.freertos.org/2020/04/using-freertos-on-armv8-m-microcontrollers.html

- [ ] [Stm intro](https://www.st.com/resource/en/application_note/dm00493651-introduction-to-stm32-microcontrollers-security-stmicroelectronics.pdf)

- [x] [C++](https://www.w3schools.in/cplusplus-tutorial/)

- [x] **https://metebalci.com/blog/hello-trustzone/**

**Comment by KurfuerstPilz** [comment]
There is an interessting blog, which describes how the call between secure and non-secure functions is working. (https://metebalci.com/blog/hello-trustzone/)

It seems that there is the possibility of using the Assembler Command SG to switch from Non-Secure to Secure execution. Once we have achieved our current goals we might be able to look into this in more detail as this might be a way to inject a NSC-Function and thus bypass the security provided by TrustZone
