### ISSUE TITLE
SecureLEDController::writeColor isn't suitable for concurrent programming, if type==onBoard

### ISSUE THREAD

**Issue by KurfuerstPilz** [HannesGitH/SWP_Telematik#50]
For some time I had the isuue that the LED behaved weird: It blinked shortly (if it blinked at all), if I used it in another thread, leaving runthread1 out semmed to do the trick (for some reason, it was not in the code when I pulled it from the branch). I realize now that this behaviour originates in the SecureLedController as every LED is either runed off or turned on, even though they are not meant to be manipulated at all. This is an issue if more than one thread tries to access these resources. I leave these line out for now

**Comment by KurfuerstPilz** [comment]
We will add mutex to protect the LED-Resources, if we have enough time left

**Comment by HannesGitH** [comment]
maybe add support for not setting the whole color, but only changing a single dimension (e.g. the red amount), while leaving the rest unchanged

**Comment by HannesGitH** [comment]
this issue is now splitted between either #51 or #52, closed for now
